[project]
name = "leafliction"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.3.0",
    "joblib>=1.5.2",
    "matplotlib>=3.10.7",
    "scikit-image>=0.25.2",
    "tqdm>=4.67.1",
]
